@startuml

left to right direction

actor "Vendedor" as v
actor "Cliente" as c

rectangle "Gestionar emprendimientos" {
    usecase "Crear emprendimiento" as UC1
    usecase "Editar emprendimiento" as UC2
    usecase "Eliminar emprendimiento" as UC3
    usecase "Listar emprendimientos" as UC4
    usecase "Consultar emprendimiento" as UC5
    usecase "Listar productos de un emprendimiento" as UC6
    usecase "Ver informacion del vendedor" as UC7
}

v --> UC1
v --> UC2
v --> UC3

UC4 <-- c
UC5 <-- c
UC6 <-- c

UC5 .> UC4 : <<extends>>
UC6 .> UC5 : <<extends>>
UC2 .> UC1 : <<extends>>
UC3 .> UC1 : <<extends>>
UC7 .> UC4 : <<extends>>
UC7 .> UC5 : <<extends>>
@enduml