@startuml

left to right direction

actor "Cliente" as c
actor "Vendedor de Punto Fijo" as vpf
actor "Domiciliario" as d
actor "Administrador" as adm

rectangle "Gestionar domicilios" {
    ' Vendedor de punto fijo
    usecase "Publicar domicilio" as UC1
    usecase "Listar domicilios" as UC2
    usecase "Consultar estado del domicilio" as UC3
    usecase "Consultar información del domiciliario" as UC4
    usecase "Confirmar salida del domiciliario" as UC5
    usecase "Aceptar solicitud de domicilio" as UC8

    ' Domiciliario
    usecase "Listar domicilios disponibles" as UC6
    usecase "Rechazar domicilio" as UC7
    usecase "Consultar información del domicilio" as UC9
    usecase "Aceptar domicilio" as UC10
    usecase "Consultar ruta en el mapa" as UC12
    usecase "Confirmar recogida del pedido" as UC13
    usecase "Confirmar entrega del pedido" as UC14
    usecase "Ingresar código de confirmación" as UC16

    ' Cliente
    usecase "Consultar estado del domicilio" as UC11
    usecase "Confirmar entrega del pedido" as UC19
    usecase "ver código de confirmación" as UC15

    ' Administrador
    usecase "Consultar domicilios" as UC20
    usecase "Cancelar domicilio" as UC21
    usecase "Listar domicilios" as UC22
}

UC1 <-- vpf
UC2 <-- vpf
UC4 <-- vpf
UC5 <-- vpf
UC8 <-- vpf

d --> UC6
d --> UC12
d --> UC13
d --> UC14

c --> UC11
c --> UC19

UC20 <-- adm
UC21 <-- adm
UC22 <-- adm

UC3 .> UC2 : <<extend>>
UC4 .> UC3 : <<extend>>
UC9 .> UC6 : <<extend>>
UC10 .> UC9 : <<extend>>
UC7 .> UC9 : <<extend>>
UC20 .> UC22 : <<extend>>

UC15 <. UC19 : <<include>>
UC14 .> UC16 : <<include>>

note right of UC1
  Solo para pedidos de domicilio ya aceptados.
  Punto A = punto fijo, punto B = ubicación del cliente.
  Un domicilio publicado no puede editarse.
end note

note right of UC9
  Muestra de dónde sale, a dónde va,
  quién lo recibe y cuánto ganaría.
end note

note right of UC12
  Disponible cuando el domicilio queda asignado
end note


@enduml
