@startuml

left to right direction

actor "Usuario" as u
actor "Cliente" as c
actor "Vendedor" as v
actor "Vendedor Ambulante" as va
actor "Vendedor de Punto Fijo" as vpf
actor "Domiciliario" as d
actor "Administrador" as adm

c --|> u
v --|> u
d --|> u
adm --|> u
va --|> v
vpf --|> v

rectangle "Ñapa" {
    usecase "Gestionar cuenta" as UC1
    usecase "Gestionar notificaciones" as UC2
    usecase "Gestionar emprendimientos" as UC3
    usecase "Gestionar productos" as UC4
    usecase "Gestionar pedidos" as UC5
    usecase "Gestionar entregas del vendedor ambulante" as UC6
    usecase "Gestionar reservas" as UC7
    usecase "Gestionar domicilios" as UC8
    usecase "Gestionar pagos" as UC9
    usecase "Gestionar comentarios y calificaciones" as UC10
    usecase "Gestionar reportes" as UC11
    usecase "Gestionar usuarios" as UC12
}

u --> UC1
u --> UC2

c --> UC3
c --> UC5
c --> UC7
c --> UC8
c --> UC9
c --> UC10
c --> UC11

v --> UC3
v --> UC4
v --> UC5
v --> UC9
v --> UC10
v --> UC11

va --> UC6
va --> UC7

vpf --> UC7
vpf --> UC8

d --> UC8
d --> UC9
d --> UC10
d --> UC11

adm --> UC8
adm --> UC9
adm --> UC10
adm --> UC11
adm --> UC12

@enduml
